### ISSUE TITLE
Docs need updating

### ISSUE THREAD

**Issue by lukehutch** [Dinoosauro/tiktok-to-ytdlp#11]
Thanks for this awesome tool.

Two things that the docs should be updated to include:

(1) When you try to paste the script into the console, you get the error that you have to type `allow pasting` first. This should probably be in your instructions:

![image](https://github.com/Dinoosauro/tiktok-to-ytdlp/assets/811305/117dd740-d426-44dc-befc-2f95727be04a)

(2) However once the scraper completes, it also looks like the download failed:

![image](https://github.com/Dinoosauro/tiktok-to-ytdlp/assets/811305/4816f26f-c1ff-4bce-97e1-9c43f3a5c55d)

These errors can be ignored, however -- the file containing URLs should have been written to the Downloads folder.

**Comment by Dinoosauro** [comment]
Hi! I'm really sorry for the late reply
Thank you for bringing up the "allow pasting" issue. I'll update the docs and add it.
While, on the second point, I think these are requests sent by the TikTok webpage (and not the script) that your browser has blocked. Maybe you're (rightfully) using an extension like uBlock Origin, or you've set your browser privacy options to block tracking domains. There shouldn't be anything to worry, as long as the scripts is downloaded on the drive
