### ISSUE TITLE
Crediting you for a userscript using your code

### ISSUE THREAD

**Issue by lihuelworks** [Dinoosauro/tiktok-to-ytdlp#12]
Hi Dinoosauro, sorry for adding this as an issue. I've written an Userscript that uses this code as a base to add a "Get list of tiktok links" button to Tiktok, and I wanted to know the best way to credit your work. The metadata links to this Github repo link, and mentions you both on the @description and on the @author tag. I've also made to sure to add credits on the Readme: https://github.com/lihuelworks/tiktok-to-ytdlp-userscript

Let me know if there is a better way to credit your work.

**Comment by Dinoosauro** [comment]
Hi! Thanks a lot for letting me know. Don't worry, the attribution is completely fine, and I really appreciate it. 
Thank you also for creating something that can be really useful!

**Comment by lihuelworks** [comment]
Na man, thanks to you, I've just stumbled into your work yesterday by mere chance, and it may be the only solution for that specific problem in all of Github (the others get kicked to the curb by tiktok anti-bot measures). Anyways, lmk if I can help you with anything, or if you're making your own userscript version, so I can link it up 👍🏻👍🏻

**Comment by Dinoosauro** [comment]
I really appreciate the kind words! Have a great day!
