### ISSUE TITLE
limit the number of fetched files

### ISSUE THREAD

**Issue by notorious-eric** [Dinoosauro/tiktok-to-ytdlp#14]
Hi, I wonder if this script can limit the number of fetched files, if we do not want all the videos. Thank you.
Also, I found that this can not fetch links from tiktok.com/search/?

**Comment by Dinoosauro** [comment]
Hi! Thanks for reporting the issues. The new update should fix all of that: you can specify from the script options a preferred number of videos to download, and the search containers are now supported. Let me know if you encounter any other issues
