### ISSUE TITLE
i keep getting an error

### ISSUE THREAD

**Issue by urmaskedboi** [Dinoosauro/tiktok-to-ytdlp#16]
i keep getting an error saying "the JSON object must be str, bytes or bytearray, not NoneType"

**Comment by Dinoosauro** [comment]
Hi! That seems to be an error of yt-dlp. Recently, TikTok has imposed stricter rules for video downloading with third-party tools. You might need to pass cookies to yt-dlp, or to change the extractor arguments for TikTok (see https://github.com/yt-dlp/yt-dlp#tiktok)

________________________________
From: urmaskedboi ***@***.***>
Sent: Sunday, May 26, 2024 12:15 AM
To: Dinoosauro/tiktok-to-ytdlp ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [Dinoosauro/tiktok-to-ytdlp] i keep getting an error (Issue #16)


i keep getting an error saying "the JSON object must be str, bytes or bytearray, not NoneType"
