### ISSUE TITLE
Incorrect quotation marks around the output template - here is the correct one via chatGPT.

### ISSUE THREAD

**Issue by jeffscottward** [Dinoosauro/tiktok-to-ytdlp#17]
The issue might be due to the incorrect quotation marks around the output template. Ensure you are using straight quotes (" "), not curly quotes (“ ”). Here's the corrected command:

`yt-dlp -a TikTokLinks.txt -o "TikTok/%(uploader)s/%(title)s - %(id)s.%(ext)s"`

**Comment by Dinoosauro** [comment]
You're right. I fixed that small issue in the README. Thanks for pointing that out!
