### ISSUE TITLE
Pass download file name (or guess from URL?)

### ISSUE THREAD

**Issue by Cassian-Andor** [Dinoosauro/tiktok-to-ytdlp#2]
Hi. This is a great script thank you. Works fantastic on Safari. However for automation, I find it cumbersome to rename the file every time.
I was thinking of making a "ViolentMonkey" script that only triggers on certain profiles (ones to download), includes your script, and then auto starts scrolling (essentially removing the need to go to console). I am not sure if the entry point would be `loadWebpage` then, or none because it's already called in the script definition.

In order to generate different txt files to pass to yt-dlp, because they all have the same filename (`TikTokLinks.txt`), you have to rename each, every time. And if you have multiple channels then it gets a bit tiring.

Would it be possible to maybe pass the channel name to your script, so that the resulting filename would be that? Or maybe for the script to auto-fetch the name? In a way that we don't need to modify the script at all, and we can just include it from other scripts (remotely) so that it's always up-to-date and whatnot.

**Comment by Dinoosauro** [comment]
Hi! Thanks a lot for the idea. You're right, keeping the same name for every download isn't the ideal solution. 

Now it's possible to change the output file name. The script will automatically look for the username, the selected hashtag etc. and it'll use that for the name. 
It's also possible to put a custom file name, if you want to change how your script saves the file you could call the `startDownload()` function with a custom file name as an argument (if you want to add extra things, like the date etc.) or edit the `scriptOptions.output_name_type` value to a string (or to one of the other automatic options). 

Thank you again for the suggestion. If there are any other things that you think they might be changed, I would be happy to look into them!
