### ISSUE TITLE
empty file

### ISSUE THREAD

**Issue by flogapis** [Dinoosauro/tiktok-to-ytdlp#23]
Hey, Hope you're doing well.

I just tested the js file and it giving me empty file. il also tested the firefox extension and i have the same problem. Am'I missing something ? 
I'm testing with this profile https://www.tiktok.com/@fullhistoiresredditfr (it's mine🙃)
Thanks

**Comment by Dinoosauro** [comment]
Hi! I tried the script and it seems to be working. Have you enabled some custom options for video downloading? 
I've also pushed an update to the script (I'll upload it on Mozilla Addons later) that adds a new method for extracting the video container. Try enabling the "get_video_container_from_e2e" option from the "advanced" object in the "scriptOptions" variable, and let me know if in that way the script works.


If you're still having issues, would you mind sending the HTML class of the video container? Maybe TikTok is rolling out a new change in the HTML layout and I'll need to fix the script. Let me know if that worked!

**Comment by flogapis** [comment]
Hey, 

It start to work when i thick the "Use the [data-e2e] attributes for getting the video container" in advanced setting.

Thanks. Have a great day

**Comment by Dinoosauro** [comment]
Glad I helped!
