### ISSUE TITLE
update request script.js

### ISSUE THREAD

**Issue by l337boi** [Dinoosauro/tiktok-to-ytdlp#25]
Regarding script.js, please make adjustments because the specifications for loading and scrolling TikTok videos have changed.

**Comment by Dinoosauro** [comment]
Hi, does the script work if you enable the `get_video_container_from_e2e` from the Advanced options? It currently works for me with or without that option enabled, so maybe TikTok is slowly rolling out changes to their webpage. If it doesn't work with that option enabled, let me know

**Comment by l337boi** [comment]
I tried it again, and it worked fine without setting any options. Thanks

**Comment by Dinoosauro** [comment]
Perfect, if you find any other issues with the script let me know and I'll try to fix them
