### ISSUE TITLE
css selector to update

### ISSUE THREAD

**Issue by lemax1216** [Dinoosauro/tiktok-to-ytdlp#26]
idk how to do pull requests cause i'm kinda new to github but the css selectors are outdated

**Comment by lemax1216** [comment]
so in the addarray function it should be like: 

    const e2eLinks = "[data-e2e=user-liked-item-list], [data-e2e=music-item], [data-e2e=user-post-item], [data-e2e=favorites-item-list], [data-e2e=challenge-item], [data-e2e=search_top-item]";
    let container = document.querySelectorAll(scriptOptions.advanced.get_video_container_from_e2e ? e2eLinks : ".tiktok-1uqux2o-DivItemContainerV2, .css-1uqux2o-DivItemContainerV2, .css-1soki6-DivItemContainerForSearch, .css-ps7kg7-DivThreeColumnItemContainer"); // Class of every video container


i could be wrong tho

**Comment by Dinoosauro** [comment]
Don't worry, I'll do that. While for the e2e list the script needs to get the single div of the video (not the list), it's possible that TikTok is changing for some users the class name. I'll update the container list, thanks for pointing that out!

**Comment by lemax1216** [comment]
:)
