### ISSUE TITLE
I don't use FIREFOX

### ISSUE THREAD

**Issue by HateFireFox96** [Dinoosauro/tiktok-to-ytdlp#28]
I use a browser that naturally blocks ads and blocks trackers, and uses less RAM than firefox.
Can't you just make an extension file that doesn't require stupid firefox to be installed or used?
NOT EVERYONE USES STUPID FIREFOX.
I refuse to re-install a web browser i never liked and never will like okay.

**Comment by Dinoosauro** [comment]
Instructions to install the extension on Chromium-based browsers are already available in [the extension README](https://github.com/Dinoosauro/tiktok-to-ytdlp/tree/main/extension#chromium).
