### ISSUE TITLE
error after scrolling

### ISSUE THREAD

**Issue by caitlingilbert** [Dinoosauro/tiktok-to-ytdlp#3]
hey! thanks for the great tool--this had been working for me, but am now hitting the following error, and not sure how to adjust the script:

`Uncaught TypeError: Cannot read properties of null (reading 'querySelector')
    at addArray (<anonymous>:44:305)
    at ytDlpScript (<anonymous>:52:5)
    at <anonymous>:26:25`

for ref I ran script.js as is, just with get_array_after_scroll set to true -- scrolling works fine and then nothing gets written out. thanks in advance!

**Comment by Dinoosauro** [comment]
Hi! Thanks a lot for reporting the issue. I've created a new method to get URL links that should fix this type of error, and I added more attributes to the old method, so both of them now should work. If you still find some pages that don't work, I would love to look into them!

**Comment by Dinoosauro** [comment]
Glad I helped!
