### ISSUE TITLE
Empty file

### ISSUE THREAD

**Issue by Cassian-Andor** [Dinoosauro/tiktok-to-ytdlp#7]
Hi!
The script is currently downloading empty files. Maybe TikTok sources changed?
It seems to scroll to the end just fine.

Tested on Chrome and Safari.

**Comment by Dinoosauro** [comment]
That's strange. I tried with that link and it worked. Maybe TikTok is doing some A/B testing with a new interface that changes the class name of the divs. 
The script looks to the `tiktok-x6y88p-DivItemContainerV2` class to get each video content. If you can, could you try to see if the class name of each video container is the same from the inspect element tab? Then the script should automatically look for links inside the div, so I think the problem could be on fetching the div class

**Comment by Dinoosauro** [comment]
Perfect, I've added both classes to the querySelector so that in any case the script should find the DivContainer class. Thank you a lot for reporting! If you encounter any other issues, let me know and I'll look into them
